apiVersion: batch/v1
kind: Job
metadata:
  name: add-home-subscriber
  namespace: home-network
spec:
  template:
    spec:
      containers:
      - name: dbctl
        image: docker.io/gradiant/open5gs-dbctl:0.10.3
        command: ["open5gs-dbctl", "add_ue_with_slice", "999700000000001", "465B5CE8B199B49FAA5F0A2EE238A6BC", "E8ED289DEBA952E4283B54E88E6183CA", "internet", "1", "ffffff"]
        env:
        - name: DB_URI
          value: "mongodb://home-open5gs-mongodb/open5gs"
      restartPolicy: Never
  backoffLimit: 4 