apiVersion: batch/v1
kind: Job
metadata:
  name: delete-old-subscriber
  namespace: home-network
spec:
  template:
    spec:
      containers:
      - name: dbctl
        image: docker.io/gradiant/open5gs-dbctl:0.10.3
        command: ["open5gs-dbctl", "remove", "999700000000001"]
        env:
        - name: DB_URI
          value: "mongodb://home-open5gs-mongodb/open5gs"
      restartPolicy: Never
  backoffLimit: 1 