customOpen5gsConfig:
  global:
    max:
      ue: 1024
  sepp:
    sbi:
      server:
        - address: 0.0.0.0
          port: 7777
      client:
        nrf:
          - uri: http://home-open5gs-nfs-nrf-sbi.home-network.svc.cluster.local:7777
    n32:
      server:
        - sender: home-sepp
          scheme: http
          address: 0.0.0.0
          port: 7443
      client:
        sepp:
          - receiver: visited-sepp
            uri: http://visited-sepp-open5gs-sepp-n32.visited-network.svc.cluster.local:7443
            plmn_id:
              mcc: "999"
              mnc: "70"
    default: {}
