customOpen5gsConfig:
  global:
    max:
      ue: 1024
  sepp:
    sbi:
      server:
        - address: 0.0.0.0
          port: 7777
      client:
        nrf:
          - uri: http://home-open5gs-nfs-nrf-sbi.home-network.svc.cluster.local:7777
    n32:
      server:
        - sender: home-sepp.home-network.svc.cluster.local
          scheme: http
          address: 0.0.0.0
          port: 7443
      n32f:
        scheme: http
        address: 0.0.0.0
      client:
        sepp:
          - receiver: visited-sepp.visited-network.svc.cluster.local
            uri: http://192.168.58.2:30526
            plmn_id:
              mcc: "001"
              mnc: "01"
    default: {} 